# Generated by Django 5.2.7 on 2025-11-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='code',
            new_name='icon',
        ),
    ]
