# Generated by Django 5.2.7 on 2025-11-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_code_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon',
            new_name='code',
        ),
    ]
